#!/usr/bin/env python3
"""Generate app/redesign.css from the redesign prototype's <style> block.

Usage:
  python3 scripts/scope-prototype-css.py redesign-handoff/prototype/vindicated-redesign.html > app/redesign.css

Every selector is scoped under `.rd` so the legacy dark pages are
unaffected (`header`/`footer` map to `.rd-hdr`/`.rd-ftr`, `:root`/`body`
map to `.rd`), and every @keyframes name is prefixed with `rd-` so it
can't collide with the ones in globals.css. Hand-written adjustments go
in app/redesign-overrides.css, never in the generated file.
"""
import re
import sys

HEADER = """/*
 * GENERATED by scripts/scope-prototype-css.py from the redesign prototype.
 * Do not edit by hand: put adjustments in app/redesign-overrides.css.
 */

/* Pages that use the redesign get a white canvas and no grain overlay. */
body:has(.rd-page){background:#fff;color:#2a0f31}
body:has(.rd-page)::after{display:none}
html:has(.rd-page){scroll-behavior:smooth;scroll-padding-top:calc(env(safe-area-inset-top,0px) + 90px)}
@media (prefers-reduced-motion:reduce){html:has(.rd-page){scroll-behavior:auto}}
"""


def split_top(s):
    parts, depth, cur = [], 0, ""
    for ch in s:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += ch
    parts.append(cur)
    return parts


def scope_selector(sel):
    sel = sel.strip()
    if sel in (":root", "body"):
        return ".rd"
    if sel == "html":
        return None
    m = re.match(r"^(header|footer)\b(.*)$", sel)
    if m:
        return (".rd-hdr" if m.group(1) == "header" else ".rd-ftr") + m.group(2)
    return ".rd " + sel


def main(path):
    html = open(path, encoding="utf-8").read()
    css = re.search(r"<style>(.*?)</style>", html, re.S).group(1)
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    keyframes = set(re.findall(r"@keyframes\s+([\w-]+)", css))

    def rename_animations(body):
        def fix(m):
            val = m.group(2)
            for k in keyframes:
                val = re.sub(r"(?<![\w-])" + re.escape(k) + r"(?![\w-])", "rd-" + k, val)
            return m.group(1) + val

        return re.sub(r"(animation(?:-name)?\s*:)([^;}]*)", fix, body)

    def clean_root(body):
        # The prototype pads :root for the iOS safe area; .rd is on several
        # elements here, so drop that padding.
        return re.sub(r"\s*padding-(top|bottom):env\(safe-area-inset-\w+,0px\);", "", body)

    def parse(block):
        out, i = [], 0
        while True:
            j = block.find("{", i)
            if j < 0:
                break
            head = block[i:j].strip()
            depth, k = 1, j + 1
            while depth:
                if block[k] == "{":
                    depth += 1
                elif block[k] == "}":
                    depth -= 1
                k += 1
            inner = block[j + 1 : k - 1].strip()
            if head.startswith("@keyframes"):
                out.append("@keyframes rd-%s{%s}" % (head.split()[1], inner))
            elif head.startswith(("@media", "@supports")):
                sub = parse(inner)
                if sub:
                    out.append(head + "{\n" + sub + "\n}")
            else:
                sels = [s for s in (scope_selector(x) for x in split_top(head)) if s]
                if sels:
                    body = rename_animations(inner)
                    if ".rd" in sels and len(sels) == 1:
                        body = clean_root(body)
                        body = body.replace('--font:"Plus Jakarta Sans"', '--font:var(--font-jakarta),"Plus Jakarta Sans"')
                    out.append(",".join(sels) + "{" + body + "}")
            i = k
        return "\n".join(out)

    sys.stdout.write(HEADER + "\n" + parse(css) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
